server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.github.ssssssu12.kakaopay.sprinkle: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace